/* Liste des cles animation encore supportees (mode assets-only). */

const ANIMATION_CORE_SETTING_KEYS = [
  'anim_enabled',
  'anim_duration_scale',
  'anim_intensity',
  'anim_scene_assets_enabled',
  'anim_scene_asset_show_hero',
  'anim_scene_asset_mobile_enabled',
  'anim_scene_asset_size',
  'anim_scene_asset_opacity',
  'anim_scene_asset_speed',
  'anim_scene_asset_fit',
  'anim_scene_asset_default_url',
  'anim_scene_asset_hero_url',
  'anim_scene_asset_about_url',
  'anim_scene_asset_skills_url',
  'anim_scene_asset_projects_url',
  'anim_scene_asset_blog_url',
  'anim_scene_asset_contact_url',
  'anim_mascots_enabled',
  'anim_mascot_show_hero',
  'anim_mascot_count',
  'anim_mascot_size',
  'anim_mascot_speed',
  'anim_mascot_opacity',
  'anim_mascot_asset_fit',
  'anim_mascot_asset_default_url',
  'anim_mascot_asset_about_url',
  'anim_mascot_asset_skills_url',
  'anim_mascot_asset_projects_url',
  'anim_mascot_asset_blog_url',
  'anim_mascot_asset_contact_url',
  'anim_sprite_wander_enabled',
  'anim_sprite_wander_size',
  'anim_sprite_wander_speed',
  'anim_sprite_wander_opacity',
  'anim_sprite_side_enabled',
  'anim_sprite_side_count',
  'anim_sprite_side_size',
  'anim_sprite_side_frequency_ms',
  'anim_sprite_side_duration_ms',
  'anim_sprite_asset_fit',
  'anim_sprite_asset_default_url',
  'anim_sprite_asset_wander_url',
  'anim_sprite_asset_side_left_url',
  'anim_sprite_asset_side_right_url',
]

module.exports = {
  ANIMATION_CORE_SETTING_KEYS,
  ANIMATION_CORE_SETTING_KEY_SET: new Set(ANIMATION_CORE_SETTING_KEYS),
}

