/* Catalogue des themes "marketplace" proposes a l'import dans l'admin. */

const THEME_MARKETPLACE_CATALOG = [
  {
    slug: 'ocean-bloom',
    name: 'Ocean Bloom',
    shortDescription: 'Ambiance marine moderne avec accent turquoise lumineux.',
    description: 'Theme propre et lumineux, ideal pour portfolio produit et web app.',
    category: 'creative',
    style: 'clean',
    author: 'Portfolio CMS Studio',
    featured: true,
    version: 1,
    tags: ['portfolio', 'clean', 'modern'],
    settings: {
      theme_dark_bg_primary: '#04121c',
      theme_dark_bg_secondary: '#07202c',
      theme_dark_bg_card: '#0b2b39',
      theme_dark_accent: '#1dd3b0',
      theme_dark_accent_light: '#71f6dd',
      theme_dark_text_primary: '#e9f8f6',
      theme_dark_text_secondary: '#8eb7bc',
      theme_dark_border: '#103845',
      theme_light_bg_primary: '#eefcf9',
      theme_light_bg_secondary: '#dff8f2',
      theme_light_bg_card: '#ffffff',
      theme_light_accent: '#17b695',
      theme_light_accent_light: '#41d8b7',
      theme_light_text_primary: '#0a2d2a',
      theme_light_text_secondary: '#3f7f78',
      theme_light_border: '#b7e7de',
      ui_font_body: 'inter',
      ui_font_heading: 'geometric',
      ui_font_mono: 'jetbrains',
      ui_radius_base: '14',
      ui_glow_strength: '1.2',
      anim_intensity: '1.1',
      anim_profile: 'balanced',
    },
  },
  {
    slug: 'midnight-neon',
    name: 'Midnight Neon',
    shortDescription: 'Look cyber contrasté, fort impact visuel.',
    description: 'Palette sombre avec neon mint, parfaite pour profils tech et IA.',
    category: 'futuristic',
    style: 'high-contrast',
    author: 'Portfolio CMS Studio',
    featured: true,
    version: 1,
    tags: ['cyber', 'dark', 'tech'],
    settings: {
      theme_dark_bg_primary: '#07060d',
      theme_dark_bg_secondary: '#0d0c18',
      theme_dark_bg_card: '#121127',
      theme_dark_accent: '#43ffd1',
      theme_dark_accent_light: '#8affea',
      theme_dark_text_primary: '#f2fbff',
      theme_dark_text_secondary: '#9ea6c6',
      theme_dark_border: '#21224a',
      theme_light_bg_primary: '#f3f6ff',
      theme_light_bg_secondary: '#e8eeff',
      theme_light_bg_card: '#ffffff',
      theme_light_accent: '#14b996',
      theme_light_accent_light: '#43ffd1',
      theme_light_text_primary: '#111529',
      theme_light_text_secondary: '#4a5a85',
      theme_light_border: '#cad7ff',
      ui_font_body: 'inter',
      ui_font_heading: 'jetbrains',
      ui_font_mono: 'jetbrains',
      ui_radius_base: '10',
      ui_glow_strength: '1.5',
      ui_transition_speed: '260',
      anim_intensity: '1.3',
      anim_profile: 'vibrant',
    },
  },
  {
    slug: 'terracotta-editorial',
    name: 'Terracotta Editorial',
    shortDescription: 'Style editorial premium, chaleureux et lisible.',
    description: 'Theme ideal pour blog long-form, contenus experts et storytelling.',
    category: 'editorial',
    style: 'warm',
    author: 'Portfolio CMS Studio',
    featured: false,
    version: 1,
    tags: ['blog', 'editorial', 'warm'],
    settings: {
      theme_dark_bg_primary: '#1f1411',
      theme_dark_bg_secondary: '#2b1b16',
      theme_dark_bg_card: '#38231c',
      theme_dark_accent: '#e38854',
      theme_dark_accent_light: '#f6ad7c',
      theme_dark_text_primary: '#f8ebe4',
      theme_dark_text_secondary: '#c8a898',
      theme_dark_border: '#523328',
      theme_light_bg_primary: '#fff8f2',
      theme_light_bg_secondary: '#fceee4',
      theme_light_bg_card: '#ffffff',
      theme_light_accent: '#c96a35',
      theme_light_accent_light: '#df8a57',
      theme_light_text_primary: '#2e1911',
      theme_light_text_secondary: '#855948',
      theme_light_border: '#e8c5b2',
      ui_font_body: 'serif',
      ui_font_heading: 'serif',
      ui_font_mono: 'jetbrains',
      ui_font_scale: '1.05',
      ui_radius_base: '9',
      ui_glow_strength: '0.7',
      anim_profile: 'minimal',
      anim_intensity: '0.8',
    },
  },
  {
    slug: 'forest-minimal',
    name: 'Forest Minimal',
    shortDescription: 'Minimalisme naturel pour portfolios freelances.',
    description: 'Look epure vert profond avec forte lisibilite mobile.',
    category: 'minimal',
    style: 'soft',
    author: 'Portfolio CMS Studio',
    featured: false,
    version: 1,
    tags: ['minimal', 'freelance', 'nature'],
    settings: {
      theme_dark_bg_primary: '#0a1411',
      theme_dark_bg_secondary: '#10201b',
      theme_dark_bg_card: '#142a23',
      theme_dark_accent: '#54c48c',
      theme_dark_accent_light: '#8ae1b5',
      theme_dark_text_primary: '#e8f6ef',
      theme_dark_text_secondary: '#8fb4a4',
      theme_dark_border: '#1f3b31',
      theme_light_bg_primary: '#f2fbf6',
      theme_light_bg_secondary: '#e4f5eb',
      theme_light_bg_card: '#ffffff',
      theme_light_accent: '#399d6e',
      theme_light_accent_light: '#54c48c',
      theme_light_text_primary: '#13261f',
      theme_light_text_secondary: '#447463',
      theme_light_border: '#b9dfcd',
      ui_font_body: 'inter',
      ui_font_heading: 'inter',
      ui_font_mono: 'jetbrains',
      ui_radius_base: '16',
      ui_glow_strength: '0.9',
      anim_profile: 'minimal',
      anim_duration_scale: '0.9',
      anim_intensity: '0.7',
    },
  },
  {
    slug: 'mono-terminal',
    name: 'Mono Terminal',
    shortDescription: 'Esthetique terminal pro pour profils engineering.',
    description: 'Theme strict et technique, parfait pour developer portfolio.',
    category: 'developer',
    style: 'mono',
    author: 'Portfolio CMS Studio',
    featured: true,
    version: 1,
    tags: ['developer', 'terminal', 'mono'],
    settings: {
      theme_dark_bg_primary: '#050707',
      theme_dark_bg_secondary: '#0c1010',
      theme_dark_bg_card: '#111818',
      theme_dark_accent: '#70ff8b',
      theme_dark_accent_light: '#a2ffb2',
      theme_dark_text_primary: '#eaf6ea',
      theme_dark_text_secondary: '#90b096',
      theme_dark_border: '#1c2b1f',
      theme_light_bg_primary: '#f5faf5',
      theme_light_bg_secondary: '#e9f4e9',
      theme_light_bg_card: '#ffffff',
      theme_light_accent: '#2d9f4a',
      theme_light_accent_light: '#64c77d',
      theme_light_text_primary: '#152116',
      theme_light_text_secondary: '#48624b',
      theme_light_border: '#c2ddc6',
      ui_font_body: 'jetbrains',
      ui_font_heading: 'jetbrains',
      ui_font_mono: 'jetbrains',
      ui_font_scale: '0.98',
      ui_radius_base: '8',
      ui_glow_strength: '1.4',
      anim_profile: 'balanced',
      anim_intensity: '1.2',
    },
  },
  {
    slug: 'sunset-soft',
    name: 'Sunset Soft',
    shortDescription: 'Palette douce orange/rose pour personal branding.',
    description: 'Theme lumineux et accueillant pour portfolio consultant ou creator.',
    category: 'personal-brand',
    style: 'soft',
    author: 'Portfolio CMS Studio',
    featured: false,
    version: 1,
    tags: ['creator', 'personal-brand', 'soft'],
    settings: {
      theme_dark_bg_primary: '#251421',
      theme_dark_bg_secondary: '#341b2f',
      theme_dark_bg_card: '#41233a',
      theme_dark_accent: '#ff8f66',
      theme_dark_accent_light: '#ffbe9e',
      theme_dark_text_primary: '#ffece3',
      theme_dark_text_secondary: '#d3b1a3',
      theme_dark_border: '#603b53',
      theme_light_bg_primary: '#fff5ef',
      theme_light_bg_secondary: '#ffe9dd',
      theme_light_bg_card: '#ffffff',
      theme_light_accent: '#e56e43',
      theme_light_accent_light: '#ff9b72',
      theme_light_text_primary: '#341e1a',
      theme_light_text_secondary: '#8b5c52',
      theme_light_border: '#efc5b7',
      ui_font_body: 'inter',
      ui_font_heading: 'geometric',
      ui_font_mono: 'jetbrains',
      ui_radius_base: '18',
      ui_glow_strength: '1',
      anim_profile: 'vibrant',
      anim_intensity: '1',
    },
  },
  {
    slug: 'graphite-pro',
    name: 'Graphite Pro',
    shortDescription: 'Theme premium neutre pour portfolio entreprise.',
    description: 'Style sobre et corporate, excellent pour agences et B2B.',
    category: 'business',
    style: 'professional',
    author: 'Portfolio CMS Studio',
    featured: true,
    version: 1,
    tags: ['agency', 'corporate', 'professional'],
    settings: {
      theme_dark_bg_primary: '#0c1014',
      theme_dark_bg_secondary: '#151b22',
      theme_dark_bg_card: '#1a2430',
      theme_dark_accent: '#5ea0ff',
      theme_dark_accent_light: '#9dc4ff',
      theme_dark_text_primary: '#e8eef8',
      theme_dark_text_secondary: '#9fb0c8',
      theme_dark_border: '#2a3848',
      theme_light_bg_primary: '#f5f8fd',
      theme_light_bg_secondary: '#eaf0fa',
      theme_light_bg_card: '#ffffff',
      theme_light_accent: '#3b74ca',
      theme_light_accent_light: '#6d9ae2',
      theme_light_text_primary: '#1c2738',
      theme_light_text_secondary: '#55657f',
      theme_light_border: '#c8d5e8',
      ui_font_body: 'system',
      ui_font_heading: 'system',
      ui_font_mono: 'jetbrains',
      ui_radius_base: '11',
      ui_glow_strength: '0.8',
      anim_profile: 'balanced',
      anim_intensity: '0.85',
    },
  },
  {
    slug: 'candy-pop',
    name: 'Candy Pop',
    shortDescription: 'Theme bold colore pour studio creatif.',
    description: 'Direction artistique audacieuse avec contrastes forts et motion vive.',
    category: 'creative',
    style: 'bold',
    author: 'Portfolio CMS Studio',
    featured: false,
    version: 1,
    tags: ['bold', 'studio', 'colorful'],
    settings: {
      theme_dark_bg_primary: '#1f1030',
      theme_dark_bg_secondary: '#2b1542',
      theme_dark_bg_card: '#361d53',
      theme_dark_accent: '#ff6cc5',
      theme_dark_accent_light: '#ff9cdd',
      theme_dark_text_primary: '#f9efff',
      theme_dark_text_secondary: '#c5aadf',
      theme_dark_border: '#4d2e6f',
      theme_light_bg_primary: '#fff4fb',
      theme_light_bg_secondary: '#ffe7f6',
      theme_light_bg_card: '#ffffff',
      theme_light_accent: '#d848a0',
      theme_light_accent_light: '#f270bf',
      theme_light_text_primary: '#3a1a46',
      theme_light_text_secondary: '#87588f',
      theme_light_border: '#efc2e4',
      ui_font_body: 'geometric',
      ui_font_heading: 'geometric',
      ui_font_mono: 'jetbrains',
      ui_radius_base: '20',
      ui_glow_strength: '1.6',
      anim_profile: 'vibrant',
      anim_intensity: '1.4',
      anim_card_lift_px: '10',
    },
  },
]

module.exports = {
  THEME_MARKETPLACE_CATALOG,
}
